### PR TITLE
new(scripts/Dockerfile): Creating a new docker image

### PR DESCRIPTION
**Pull request by Orenef11**
Create a new docker image with following changes:
* Upgrade Python version from `3.7` to `3.8`
* Upgrade the following packages:
  * Upgrade `PyYAML` package from `5.1.1` to `6.0`
  * Upgrade `psutil` package from `5.6.3` to `5.9.0`
* Update the name of the docker in the README.md file
Fixes https://github.com/scylladb/scylla-java-driver-matrix/pull/2
Fixes https://github.com/scylladb/scylla-java-driver-matrix/pull/3

### CODE REVIEW

**Comment by Orenef11** [comment]
@fruch 
Can I create the new docker image and push it to Scylla's dockerhub?

**Comment by Orenef11** [comment]
@fruch @roydahan 
The PR ready to review.
Please `new-docker-required` label.

**Comment by fruch** [comment]
Docker is built and pushed

**Review by fruch — APPROVED** [review]
LGTM

**Pull request merged**
