### PR TITLE
fix handle of new scylla forks

### PR DESCRIPTION
**Pull request by fruch**
scylla java-driver fork move to use a new format `4.14.1.0` for it's tags.

Fix: scylladb/qa-tasks#1197

### Testing
- [ ] - https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/java-driver-matrix-test/80/

### CODE REVIEW

**Comment by fruch** [comment]
trying this in staging:

https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/java-driver-matrix-test/64/

**Review by roydahan — APPROVED** [review]

**Comment by fruch** [comment]
@roydahan not sure what you approved here, but if we merge this, the job would mostly fail.

it's need much more work on each version there to figure out those failure, and why the test filtering isn't working as expected.
cause some of the failure are test we supposed to be not running.

**Comment by roydahan** [comment]
I approve the direction.
The analysis of failures can be done after the merge if we already support these driver versions.
Also, we can involve the driver team to help with analysis.

**Comment by roydahan** [comment]
But why do we have so many failures for 3.11?

**Comment by fruch** [comment]
> But why do we have so many failures for 3.11?
> 

I don't know, didn't had the chance to look into them.

**Pull request merged**
